// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWJhnHedyeem7RNMpzgdpULJ_wWxmkFio',
    appId: '1:215871862411:web:bf5638945030a6a9bec68e',
    messagingSenderId: '215871862411',
    projectId: 'chatter-6ed0d',
    authDomain: 'chatter-6ed0d.firebaseapp.com',
    storageBucket: 'chatter-6ed0d.firebasestorage.app',
    measurementId: 'G-D2451YCMKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFUvEHK18TUV59AxWr35sa3SjstgHeXQ',
    appId: '1:215871862411:android:d2dc8e87e8520c9fbec68e',
    messagingSenderId: '215871862411',
    projectId: 'chatter-6ed0d',
    storageBucket: 'chatter-6ed0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBStcUsNP4UXX1jTM3Eo8Tqnr7_1M1CkMA',
    appId: '1:215871862411:ios:b189f9f38bf2523bbec68e',
    messagingSenderId: '215871862411',
    projectId: 'chatter-6ed0d',
    storageBucket: 'chatter-6ed0d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBStcUsNP4UXX1jTM3Eo8Tqnr7_1M1CkMA',
    appId: '1:215871862411:ios:b189f9f38bf2523bbec68e',
    messagingSenderId: '215871862411',
    projectId: 'chatter-6ed0d',
    storageBucket: 'chatter-6ed0d.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWJhnHedyeem7RNMpzgdpULJ_wWxmkFio',
    appId: '1:215871862411:web:4b70debcbe07c4e9bec68e',
    messagingSenderId: '215871862411',
    projectId: 'chatter-6ed0d',
    authDomain: 'chatter-6ed0d.firebaseapp.com',
    storageBucket: 'chatter-6ed0d.firebasestorage.app',
    measurementId: 'G-K9YRVCN167',
  );
}
